name: BuildCExtension
on:
  push:
    branches: [ master, develop, build/poetry-and-ci-workflow ]

jobs:
  build:
    name: Build release

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # TODO: Get this working on ubuntu-latest. Refuses to build, and no idea why
        #   Left in as doesn't break anything at least
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.6.1
      # Install requirements and build extension
      - name: Install requirements and build extension
        run: |
          poetry install --with dev
          python -c "import shutil, glob, os; [shutil.copy(f, '.') for f in glob.glob('mapanalyzerext*') if not os.path.exists(os.path.join('.', os.path.basename(f)))]"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_python${{ matrix.python-version }}
          path: |
            ./mapanalyzerext*
            mapanalyzerext*
